# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 763c35488d3c2043fe481410f449ae40cef379355eb085653369d308e2fcfdb79c65da9f424d4470f409323f255121e30943c66c80dda368d3dd190d6a01b138

test:
  secret_key_base: effcbe0378c27fce328c719fe98a16871aec7e9c3185cacc16bb4231bae9e61ae3de0e22d7f99aa67ac407fd91177fbb664606f3be422f56cbf63bbc603bd68e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
